Loaded Projects
openshift/svt pull request #658
Opened 2021-02-17 18:05 UTC by paigerube14

Updating [TC](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-9461) to be able to use python cluster loader and separating out the cluster loader part to be able to easily run without pbench.

2021-03-02 20:12 UTC, mffiedler requested changes

2021-03-02 20:12 UTC, mffiedler commented on openshift_scalability/ci/scripts/create-loaded-projects.sh
> +  VIPERCONFIG=$MY_CONFIG openshift-tests run-test "[sig-scalability][Feature:Performance] Load cluster should populate the cluster [Slow][Serial]"
Given the relative paths inside of config/golang/configCreateLoadedProjects.yaml this failed for me when I ran it from ci/scripts directory.   Which has been a weak point of golang CL and our directory structure.   I had to add the following line above the call to openshift-tests:
  cd ../../content
to get the ./<template-name> templates in configCreateLoadedProjects.yaml to work. 

We can either update the script or the yaml file, but I think we should be able to run the script from ci/scripts.

2021-03-03 18:32 UTC, mffiedler commented on openshift_scalability/config/golang/configCreateLoadedProjects.yaml
> +          file: ../../route-template.json
These should all be under content

2021-05-26 14:52 UTC, paigerube14 commented
Updated pointers to templates in golang config.

Having an issue that the objects created by the templates (not pods) are not being created in the project, they are getting created in the default project. Still investigating this issue

2021-05-31 15:16 UTC, mffiedler reviewed
In general, LGTM.  Please squash.  Curious as to why you picked lower default project and pod numbers?

2021-06-01 16:15 UTC, mffiedler approved these changes
Tested python and golang - all working well.   LGTM

2021-06-01 16:15 UTC, merged

2021-06-01 16:23 UTC, paigerube14 commented
Thanks Mike! Sorry this took so long to make updates.